
# command to install dependencies
language: python
python:
  - 2.7
notifications:
  email: false
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
  - pip install -e .
# env:
#   - THEANO_FLAGS='floatX=float32'
# Run test
script: python setup.py all_test
# only integrate the master branch
branches:
  only:
    - master
# web hooks (eg. gitter)
notifications:
  # slack: stanfordnlp:<SLACK CODE>  # we don't have this integration set up
  # webhooks:
  #   on_success: change  # options: [always|never|change] default: always
  #   on_failure: always  # options: [always|never|change] default: always
  #   on_start: false     # default: false
  email:
    on_success: never # [always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
